export { default as DuotoneCarrot } from '@/assets/icons/DuotoneCarrot.vue'
export { default as DuotoneChevronRight } from '@/assets/icons/DuotoneChevronRight.vue'
export { default as DuotoneClearNight } from '@/assets/icons/DuotoneClearNight.vue'
export { default as DuotoneDiscord } from '@/assets/icons/DuotoneDiscord.vue'
export { default as DuotoneGridThree } from '@/assets/icons/DuotoneGridThree.vue'
export { default as DuotoneHome } from '@/assets/icons/DuotoneHome.vue'
export { default as DuotoneSunny } from '@/assets/icons/DuotoneSunny.vue'
export { default as DuotoneCommand } from '@/assets/icons/DuotoneCommand.vue'
export {default as DuotoneContentCopy} from '@/assets/icons/DuotoneContentCopy.vue'

export { default as OutlineCarrot } from '@/assets/icons/OutlineCarrot.vue'
export { default as OutlineChevronRight } from '@/assets/icons/OutlineChevronRight.vue'
export { default as OutlineClearNight } from '@/assets/icons/OutlineClearNight.vue'
export { default as OutlineDiscord } from '@/assets/icons/OutlineDiscord.vue'
export { default as OutlineGridThree } from '@/assets/icons/OutlineGridThree.vue'
export { default as OutlineHome } from '@/assets/icons/OutlineHome.vue'
export { default as OutlineSunny } from '@/assets/icons/OutlineSunny.vue'
export { default as OutlineCommand } from '@/assets/icons/OutlineCommand.vue'
export {default as OutlineContentCopy} from '@/assets/icons/OutlineContentCopy.vue'

export { default as SolidCarrot } from '@/assets/icons/SolidCarrot.vue'
export { default as SolidChevronRight } from '@/assets/icons/SolidChevronRight.vue'
export { default as SolidClearNight } from '@/assets/icons/SolidClearNight.vue'
export { default as SolidDiscord } from '@/assets/icons/SolidDiscord.vue'
export { default as SolidGridThree } from '@/assets/icons/SolidGridThree.vue'
export { default as SolidHome } from '@/assets/icons/SolidHome.vue'
export { default as SolidSunny } from '@/assets/icons/SolidSunny.vue'
export { default as SolidCommand } from '@/assets/icons/SolidCommand.vue'
export {default as SolidContentCopy} from '@/assets/icons/SolidContentCopy.vue'
