export { default as DuotoneCarrot } from '@/assets/icons/DuotoneCarrot.vue'
export { default as DuotoneChevronRight } from '@/assets/icons/DuotoneChevronRight.vue'
export { default as DuotoneClearNight } from '@/assets/icons/DuotoneClearNight.vue'
export { default as DuotoneDiscord } from '@/assets/icons/DuotoneDiscord.vue'
export { default as DuotoneGridThree } from '@/assets/icons/DuotoneGridThree.vue'
export { default as DuotoneHome } from '@/assets/icons/DuotoneHome.vue'
export { default as DuotoneSunny } from '@/assets/icons/DuotoneSunny.vue'
export { default as DuotoneCommand } from '@/assets/icons/DuotoneCommand.vue'
export { default as DuotoneContentCopy } from '@/assets/icons/DuotoneContentCopy.vue'
export { default as DuotonePlus } from '@/assets/icons/DuotonePlus.vue'
export { default as DuotoneCheckCrFr } from '@/assets/icons/DuotoneCheckCrFr.vue'
export { default as DuotoneSend } from '@/assets/icons/DuotoneSend.vue'
export { default as DuotoneMicrochip } from '@/assets/icons/DuotoneMicrochip.vue'
export { default as DuotoneCrown } from '@/assets/icons/DuotoneCrown.vue'
export { default as DuotoneUserGroup } from '@/assets/icons/DuotoneUserGroup.vue'
export { default as DuotoneMenu } from '@/assets/icons/DuotoneMenu.vue'
export {default as DuotoneClose } from '@/assets/icons/DuotoneClose.vue'
export {default as DuotoneCheck} from '@/assets/icons/DuotoneCheck.vue'

export { default as OutlineCarrot } from '@/assets/icons/OutlineCarrot.vue'
export { default as OutlineChevronRight } from '@/assets/icons/OutlineChevronRight.vue'
export { default as OutlineClearNight } from '@/assets/icons/OutlineClearNight.vue'
export { default as OutlineDiscord } from '@/assets/icons/OutlineDiscord.vue'
export { default as OutlineGridThree } from '@/assets/icons/OutlineGridThree.vue'
export { default as OutlineHome } from '@/assets/icons/OutlineHome.vue'
export { default as OutlineSunny } from '@/assets/icons/OutlineSunny.vue'
export { default as OutlineCommand } from '@/assets/icons/OutlineCommand.vue'
export { default as OutlineContentCopy } from '@/assets/icons/OutlineContentCopy.vue'
export { default as OutlinePlus } from '@/assets/icons/OutlinePlus.vue'
export { default as OutlineCheckCrFr } from '@/assets/icons/OutlineCheckCrFr.vue'
export { default as OutlineSend } from '@/assets/icons/OutlineSend.vue'
export { default as OutlineMicrochip } from '@/assets/icons/OutlineMicrochip.vue'
export { default as OutlineCrown } from '@/assets/icons/OutlineCrown.vue'
export { default as OutlineUserGroup } from '@/assets/icons/OutlineUserGroup.vue'
export { default as OutlineMenu } from '@/assets/icons/OutlineMenu.vue'
export { default as OutlineClose } from '@/assets/icons/OutlineClose.vue'
export { default as OutlineCheck} from '@/assets/icons/OutlineCheck.vue'

export { default as SolidCarrot } from '@/assets/icons/SolidCarrot.vue'
export { default as SolidChevronRight } from '@/assets/icons/SolidChevronRight.vue'
export { default as SolidClearNight } from '@/assets/icons/SolidClearNight.vue'
export { default as SolidDiscord } from '@/assets/icons/SolidDiscord.vue'
export { default as SolidGridThree } from '@/assets/icons/SolidGridThree.vue'
export { default as SolidHome } from '@/assets/icons/SolidHome.vue'
export { default as SolidSunny } from '@/assets/icons/SolidSunny.vue'
export { default as SolidCommand } from '@/assets/icons/SolidCommand.vue'
export { default as SolidContentCopy } from '@/assets/icons/SolidContentCopy.vue'
export { default as SolidPlus } from '@/assets/icons/SolidPlus.vue'
export { default as SolidCheckCrFr } from '@/assets/icons/SolidCheckCrFr.vue'
export { default as SolidSend } from '@/assets/icons/SolidSend.vue'
export { default as SolidMicrochip } from '@/assets/icons/SolidMicrochip.vue'
export { default as SolidCrown } from '@/assets/icons/SolidCrown.vue'
export { default as SolidUserGroup } from '@/assets/icons/SolidUserGroup.vue'
export { default as SolidMenu } from '@/assets/icons/SolidMenu.vue'
export { default as SolidClose } from '@/assets/icons/SolidClose.vue'
export { default as SolidCheck} from '@/assets/icons/SolidCheck.vue'

export { default as Logo } from '@/assets/icons/Logo.vue'
